server:
  port: 8080
  servlet:
    context-path: /book-shop/api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/book_shop"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 2503
